kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-smart-farm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-smart-farm
  template:
    metadata:
      labels:
        app: react-smart-farm
    spec:
      containers:
      - name: react-smart-farm
        image: nakharinaroon/react-smart-farm:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "300m"
          limits:
            memory: "200Mi"
            cpu: "600m"
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: react-smart-farm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: react-smart-farm    