kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
    
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - image: react-smart-farm-frontend:v1
        name: frontend-deployment
        ports:
        - containerPort: 80
          name: http-server
---
kind: Service
apiVersion: v1
metadata:
  name:  frontend-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend-deployment